# Generated by Django 5.1.1 on 2024-09-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
