# Generated by Django 5.1.1 on 2024-09-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookmodel_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
